SMART_CLIENT_ID = '9644d85e-07f0-4962-a78b-ab1bfe39c6d8'
SMART_CLIENT_SECRET = 'APOO8c_OjK4DrcwoTYp82KUv2LrRvD_hlVinoZzqoxO5EPUZhprbb4azfXp8qTdMFxdviSQIKr7SMswVpR4SSVc'
SMART_SERVICE_ROOT = 'https://sb-fhir-dstu2.smarthealthit.org/smartdstu2/data'
SMART_SCOPE = 'openid profile offline_access patient/*.*'
JWT_SECRET = 'itsaseekrit'
